### ISSUE TITLE
samuraiwtf login incorrect

### ISSUE THREAD

**Issue by jfreedrice** [SamuraiWTF/samuraiwtf#83] opened 2019-05-31 14:50 UTC
I am using the u: samurai and p: samurai, but it is not taking my login information. What could be causing this issue? I installed just the target VM if that helps. Let me know if there is any other info needed to address this problem. Thanks!

**Comment by secureideas** [comment] 2019-05-31 14:53
Did you build using Vagrant?   And did the build complete?

**Comment by jfreedrice** [comment] 2019-05-31 15:13
@secureideas Yes, I am using Vagrant v. 2.2.4 and the build did complete. It is being hosted in VirtualBox and appears to be fully functional. I even ran the vagrant reload command as instructed in the readme.

**Comment by jfreedrice** [comment] 2019-05-31 15:24
I found this mentioning an invalid user near the end of when I was first setting up the target VM, here is the output:

    `target: Exiting with failure status due to previous errors
    target: /opt/targets/client-side-attacks-lab/targets/cors.dem
    target: setting up professionallyevil.wtf
    target: /var/www /opt/targets/client-side-attacks-lab/targets/cors.dem
    target: chown:
    target: invalid user: ‘samurai:samurai’
    target: chown:
    target: invalid user: ‘samurai:samurai’
    target: /opt/targets/client-side-attacks-lab/targets/cors.dem
    target: setting up amoksecurity.wtf
    target: /var/www /opt/targets/client-side-attacks-lab/targets/cors.dem
    target: chown:
    target: invalid user: ‘samurai:samurai’
    target: chown:
    target: invalid user: ‘samurai:samurai’
    target: /opt/targets/client-side-attacks-lab/targets/cors.dem
    target: All finished!`

**Comment by secureideas** [comment] 2019-05-31 17:15
Are you using the Next branch or master?

**Comment by jfreedrice** [comment] 2019-05-31 18:07
@secureideas The master branch, is there something I missed that is important in the next branch?

**Comment by secureideas** [comment] 2019-05-31 18:14
Nope.  We are moving to including Ansible scripts in Next, so it changes my troubleshooting.  :)

Kevin

**Comment by secureideas** [comment] 2019-05-31 18:17
Ahhh figured it out here.   The issue is that you created just the targets.  The samurai user is built in the userenv.sh file, which is not run in a target only build.  The user is vagrant:vagrant.

This will change when Next becomes master.

**Closed by secureideas** 2019-05-31 18:17 UTC

**Comment by jfreedrice** [comment] 2019-05-31 18:26
@secureideas Thank you! That solved my issue!
